# Start with the golang v1.13 image
FROM golang:1.21


ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Set a working directory
WORKDIR /go/src/app
# Copy the package files
COPY . .
# CMD cd worker_service/microservice

# Install all go_modules
# RUN go mod tidy

WORKDIR /go/src/app/worker_service/microservice
# Build the project
RUN go build -a -installsuffix cgo -o app ./bin
